### ISSUE TITLE
Doesn't work, just opens game without change.

### ISSUE THREAD

**Issue by Vad0mel** [Leo40Git/SteamPriorityLauncher#1] opened 2022-12-26 12:39 UTC
I tested and priority and affinity does not work! No errors and it's useless without that functionality.
The shortcut was made by the tutorial, but it still did not work.
I opened task manager after the shortcut and the process had default affinities and priority.

**Comment by Leo40Git** [comment] 2022-12-26 13:46
Please provide:
- The game ID/store link to the game you are trying to open.
- The EXE name of said game.
- The shortcut you're using to run SteamPriorityLauncher.

**Comment by Vad0mel** [comment] 2022-12-30 11:00
-gameID 440
-gameExe hl2.exe
Downloads\SteamPriorityLauncher.exe -gameID 440 -gameExe hl2.exe -priority A

**Comment by Vad0mel** [comment] 2022-12-30 11:01
Not full shortcut for privacy reasons

**Comment by Leo40Git** [comment] 2022-12-30 12:00
Does the launcher show an error, or does it close automatically?

**Comment by Vad0mel** [comment] 2022-12-30 13:50
It launches the game without additions
I checked with task manager

**Comment by Leo40Git** [comment] 2022-12-30 14:13
This does not answer my question.

The launcher should open a console window when you open it. If an error occurs, it prints an error and waits for you to press any key to close. If an error does not occur, it closes without waiting.

If the launcher console closes without an error but the game process does not have the priority/affinity set, then this is outside of what I can fix (since this means that Windows is telling the launcher that it successfully changed the process' priority/affinity when it didn't).

**Comment by Vad0mel** [comment] 2022-12-31 07:50
What a shame, that's the exact thing, that happens

**Comment by Vad0mel** [comment] 2022-12-31 07:56
Anyway, I had some other way of achieving core affinity with less code using empty link with this pasted inside:
C:\Windows\System32\cmd.exe /C start "" /affinity FF00 "C:\Program Files (x86)\Steam\Steam.exe" -applaunch 440
The problem with it is that the Steam.exe also has the same affinity as the game and no priority, but I think it could have the priority command added.

**Comment by Vad0mel** [comment] 2022-12-31 08:04
I think this should work for me:
C:\Windows\System32\cmd.exe /C start "" /affinity FF00 /AboveNormal "C:\Program Files (x86)\Steam\Steam.exe" -applaunch 440
Also a little explainer on the affinity, FF00 is HEX value from converted binary 1111111100000000, representing thread affinity layout, where the first binary value is the last core and so on.

**Comment by Leo40Git** [comment] 2022-12-31 08:05
Closing this since I cannot reproduce, and you've found an alternative.

**Closed as not planned by Leo40Git** 2022-12-31 08:05 UTC
